mayinTarlasi/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mayinTarlasi.Models.Entity;
using System.Data.Entity;

namespace mayinTarlasi.Controllers
{
    public class DetailsController : Controller
    {
        // GET: AboutPageDetails
        public ActionResult Index()
        {
            return View();
        }
        MVCTestEntities2 db = new MVCTestEntities2();
        public ActionResult ScoreTable()
        {
            using (var datamodel = new MVCTestEntities2())
            {
                var j = datamodel.TBLuserDatas.Include(a => a.TBLgameDatas).OrderByDescending(a => a.TBLgameDatas.FirstOrDefault().Score).ToList();
                return View(j);
            }
        }
        public ActionResult GetDataFrom()
        {
            var degerler = db.TBLgameDatas.ToList();
            return View("ScoreTable");
        }
        public ActionResult AboutGame()
        {
            return View();
        }
        public ActionResult HowToPlay()
        {
            return View();
        }
        public bool PmSender(string Message, int Receiver)
        {
            if (Session["ID_Gamedata"] != null)
            {
                var SenderId = Convert.ToInt32(Session["ID_Gamedata"]);
                PersonelMessage PersonelMessager = new PersonelMessage();
                if (PersonelMessager != null)
                {
                    PersonelMessager.SenderID = SenderId;
                    PersonelMessager.ReceiverID = Receiver;
                    PersonelMessager.Message = Message;
                    PersonelMessager.Date = DateTime.Now;
                    db.PersonelMessages.Add(PersonelMessager);
                    db.SaveChanges();
                }
            }
            return true;
        }
    }
}

mayinTarlasi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @*//IMPLEMENTS*@
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    @*IMPLEMENTS END*@
    <style>
        * {
            font-family: 'Quicksand', sans-serif;
        }

        .Notificationbar {
            background-color: #4c3e3e;
            display: none;
            margin-right: 14px;
            margin-top: 0px;
            padding: 10px;
            word-break: break-word;
            color: white;
        }

        .notifications {
            color: grey;
            padding-top: 29px;
            padding: 2px;
            margin-top: 14px;
            border-radius: 2px;
            font-size: 18px;
        }
    </style>

    <title>Mayın Tarlası</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                </button>
                <div>
                    @Html.ActionLink("Mayın Tarlası", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Oyun Bilgileri", "ScoreTable", "Details")</li>
                    <li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @{
                        if (Session["IsLoggedIn"] != null)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="notCount" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-bell" aria-hidden="true"></span> <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Hesabım", "myAccount", "Account")</li>
                            <li>@Html.ActionLink("Çıkış Yap", "LogOut", "Account")</li>

                        }
                        else
                        {
                            <li>@Html.ActionLink("Kayıt Ol", "CreateUser", "Account")</li>
                            <li>@Html.ActionLink("Giriş Yap", "Login", "Account")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>
<script>
    $("#notifications").click(function () {
        $(".Notificationbar").toggle(300);
    });
</script>

mayinTarlasi/Views/Shared/_MainLayout.cshtml
@{
    ViewBag.Title = "_MainLayout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">

            </div>
            <ul class="nav navbar-nav">
                <li class="active">
                <li>@Html.ActionLink("Rekorlar", "ScoreTable", "Details")</li>
                <li>@Html.ActionLink("Nasıl Oynanır", "HowToPlay", "Details")</li>
                <li>@Html.ActionLink("Oyun Hakkında", "AboutGame", "Details")</li>
            </ul>

        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>